#! /bin/bash

# your solution for splab1
# Variant 16
total=$(cut -d '"' -f1,4 $2 | grep -v '"-' | cut -d ' ' -f1 | sort | uniq -c | sort -n -r | head -$1 | awk '{sum+=$1} END {print sum}')
res=$(cut -d '"' -f1,4 $2 | grep -v '"-' | cut -d ' ' -f1 | sort | uniq -c | sort -n -r | head -$1 | awk '{printf(NR ". %s - %d - %.1f%% \n", $2, $1, $1 / '"$total"' * 100)}')

echo "$res"
